name: pr

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  pr-check-branch-name:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check branch name
        uses: ./.github/actions/check-pr-branch-name

  pr-auto-approve:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auto approve if author is specific user
        uses: ./.github/actions/auto-approve-pr
        with:
          pr-auto-approve-bot-token: ${{ secrets.PR_AUTO_APPROVE_BOT_TOKEN }}

  get-version:
    runs-on: ubuntu-22.04
    outputs:
      version-package: ${{ steps.get-version.outputs.version-package }}
      version-major: ${{ steps.get-version.outputs.version-major }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Get version
        id: get-version
        uses: ./.github/actions/get-version
        with:
          version-file-path: "src/Version.props"

  pr-build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .net core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.416

      - name: Build solution - ${{ matrix.configuration }}
        uses: ./.github/actions/dotnet-command
        with:
          command: build
          configuration: ${{ matrix.configuration }}
          working-directory: ./src/BasaltIconsGenerator

